export const LabField = [
    "Due Date",
    "Sample Type",
    "Material",
    "Client",
    "Packing Type",
    "Analysis Type",
    "Certificate",
    "Sending Date",
    "Sample Date",
    "Weight(actual)",
    "Charge",
    "Remark",
    "Delivering.Address.Name1",
    "Delivering.Address.Title",
    "Delivering.Address.Country",
    "Delivering.Address.Name2",
    "Delivering.Address.Name3",
    "Delivering.Address.Street",
    "Delivering.Address.ZIP",
    "CustomerProductCode",
    "E-mail Address",
    "FetchDate",
    "OrderId",
    "Pos.ID",
    "Weight(target)",
];
export const AnalField = ["Analysis Type", "Norm", "Objectives", "Remark"];
export const ClientField = [
    "Name",
    "Country B",
    "Zip Code B",
    "City B",
    "Address B",
    "Address2 B",
];
