export const header = [
  { key: "_id", label: "ID" },
  { key: "due_date", label: "Due Date" },
  { key: "sample_type", label: "Sample Type" },
  { key: "productCode", label: "Customer P.O.no" },
  { key: "material", label: "Material" },
  { key: "material_category", label: "Material Category" },
  { key: "client", label: "Client" },
  { key: "packing_type", label: "Packing Type" },
  { key: "a_types", label: "Analysis Type" },
  { key: "c_types", label: "Certificate" },
  { key: "sending_date", label: "Sending Date" },
  { key: "sample_date", label: "Sample Date" },
  { key: "distributor", label: "Distributor" },
  { key: "geo_locaion", label: "Geo Location" },
  { key: "remark", label: "Remark" },
  { key: "weight", label: "Weight" },
  { key: "material_left", label: "Material Left" },
  { key: "lot_number", label: "Lot Number" },
  { key: "stock_sample", label: "Stock Sample" },
  { key: "delivering_address_name1", label: "Delivering.Address.Name1" },
  { key: "delivering_address_title", label: "Delivering.Address.Title" },
  { key: "delivering_address_country", label: "Delivering.Address.Country" },
  { key: "delivering_address_name2", label: "Delivering.Address.Name2" },
  { key: "delivering_address_name3", label: "Delivering.Address.Name3" },
  { key: "delivering_address_street", label: "Delivering.Address.Street" },
  { key: "delivering_address_zip", label: "Delivering.Address.ZIP" },
  { key: "delivering_customer_product_code", label: "CustomProductCode" },
  { key: "delivering_email_address", label: "E-mail Address" },
  { key: "delivering_fetch_date", label: "Fetch Date" },
  { key: "delivering_order_id", label: "Order.ID" },
  { key: "delivering_pos_id", label: "Pos.ID" },
  { key: "delivering_w_target", label: "Weight(target)" },
];

export const excel_header = [
  { key: "_id", label: "ID" },
  { key: "due_date", label: "Due Date" },
  { key: "sample_type", label: "Sample Type" },
  { key: "productCode", label: "Customer P.O.no" },
  { key: "material", label: "Material" },
  { key: "material_category", label: "Material Category" },
  { key: "client", label: "Client" },
  { key: "packing_type", label: "Packing Type" },
  { key: "a_types", label: "Analysis Type" },
  { key: "c_types", label: "Certificate" },
  { key: "sending_date", label: "Sending Date" },
  { key: "sample_date", label: "Sample Date" },
  { key: "distributor", label: "Distributor" },
  { key: "geo_locaion", label: "Geo Location" },
  { key: "remark", label: "Remark" },
  { key: "weight", label: "Weight" },
  { key: "weight_comment", label: "Weight Comment" },
  { key: "material_left", label: "Material Left" },
  { key: "lot_number", label: "Lot Number" },
  { key: "stock_sample", label: "Stock Sample" },
  { key: "aT_validate", label: "AnalysisType Validate" },
  { key: "stock_specValues", label: "Stock Spec Values" },
  { key: "stock_weights", label: "Stock Weights" },
  { key: "delivering_address_name1", label: "Delivering.Address.Name1" },
  { key: "delivering_address_title", label: "Delivering.Address.Title" },
  { key: "delivering_address_country", label: "Delivering.Address.Country" },
  { key: "delivering_address_name2", label: "Delivering.Address.Name2" },
  { key: "delivering_address_name3", label: "Delivering.Address.Name3" },
  { key: "delivering_address_Place", label: "Delivering.Address.Place" },
  { key: "delivering_address_street", label: "Delivering.Address.Street" },
  { key: "delivering_address_zip", label: "Delivering.Address.ZIP" },
  { key: "delivering_customer_product_code", label: "CustomProductCode" },
  { key: "delivering_email_address", label: "E-mail Address" },
  { key: "delivering_fetch_date", label: "Fetch Date" },
  { key: "delivering_order_id", label: "Order.ID" },
  { key: 'delivering_customer_order_id', label: 'Customer OrderID' },
  { key: "delivering_pos_id", label: "Pos.ID" },
  { key: "delivering_w_target", label: "Weight(target)" },
  { key: "deliveryId", label: "Delivery ID" },
];


export const analysis_fields = [
  { key: "analysisType", label: "Analysis Type" },
  { key: "norm", label: "Norm" },
  { key: "objectives", label: "Objectives" },
  { key: "remark", label: "Remark" }
]

export const client_fields = [
  { key: "name", label: "Name" },
  { key: "countryB", label: "Country B" },
  { key: "zipCodeB", label: "Zip Code B" },
  { key: "cityB", label: "City B" },
  { key: "addressB", label: "Address B" },
  { key: "address2B", label: "Address2 B" }
]

export const object_fields = [
  { key: "limitValue", label: "Value" },
  { key: "author", label: "Author" },
  { key: "update_date", label: "Date" },
  { key: "reason", label: "Reason" },
  { key: "accept", label: "Accept" },
  { key: "comment", label: "Comment" },
];

export const weight_fields = [
  { key: "weight", label: "Weight" },
  { key: "author", label: "Author" },
  { key: "update_date", label: "Update Date" },
  { key: "comment", label: "Comment" },
];

export const charge_fields = [
  { key: "charge", label: "Charge Date" },
  { key: "author", label: "Author" },
  { key: "update_date", label: "Update Date" },
  { key: "comment", label: "Comment" },
];

export const laboratory_columns = [
  { key: "sample_type", label: "Sample Type" },
  { key: "client", label: "Client" },
  { key: "material", label: "Material" },
  { key: "material_category", label: "Material Category" },
  { key: "packing_type", label: "Packing Type" },
  { key: "a_types", label: "Analysis Type" },
  { key: "c_types", label: "Certificate Type" },
  { key: "due_date", label: "Due Date" },
  { key: "sample_date", label: "Sample Date" },
  { key: "distributor", label: "Distributor" },
  { key: "geo_location", label: "Geo-location" },
  { key: "remark", label: "Remark" },
  { key: "name1", label: "Delivering.Address.Name1" },
  { key: "name2", label: "Delivering.Address.Name2" },
  { key: "name3", label: "Delivering.Address.Name3" },
  { key: "title", label: "Delivering.Address.Title" },
  { key: "country", label: "Delivering.Address.Country" },
  { key: "place", label: "Delivering.Address.Place" },
  { key: "street", label: "Delivering.Address.Street" },
  { key: "zipcode", label: "Delivering.Address.ZIP" },
  { key: "productCode", label: "Customer Product Code" },
  { key: "email", label: "E-mail Address" },
  { key: "fetchDate", label: "Fetch Date" },
  { key: "orderId", label: "Order.ID" },
  { key: "customer_orderId", label: "Customer Order ID" },
  { key: "posId", label: "Pos.ID" },
  { key: "w_target", label: "Weight(target)[kg]" }
]

export const import_column_list = [
  { key: 'Artikel', label: "Material/PackingId" },
  { key: 'Artikeltext', label: "[Do not use]" },
  { key: 'Auftragsnummer', label: "Customer Order ID" },
  { key: 'Beleg', label: "Order.ID" },
  { key: 'Fremdartikelnummer', label: "Customer Product Code" },
  { key: 'Kundennummer', label: "Client" },
  { key: 'Ladedatum', label: "Fetch Date" },
  { key: 'Lf.adr. E-Mail', label: "E-mail Address" },
  { key: 'Lf.adr. Land', label: "Delivering.Address.Country" },
  { key: 'Lf.adr. Name 1', label: "Delivering.Address.Name1" },
  { key: 'Lf.adr. Name 2', label: "Delivering.Address.Name2" },
  { key: 'Lf.adr. Name 3', label: "Delivering.Address.Name3" },
  { key: 'Lf.adr. Ort', label: "Delivering.Address.Place" },
  { key: 'Lf.adr. PLZ', label: "Delivering.Address.ZIP" },
  { key: 'Lf.adr. Stra�e', label: "Delivering.Address.Street" },
  { key: 'Menge (PE)', label: "Weight(target)[kg]" },
  { key: 'Pos. Liefer-/Leistungsdatum', label: "Fetch Date" },
  { key: 'Pos. Nummer', label: "Pos.ID" },
  { key: 'Versanddatum', label: "Due Date" }
]